### ISSUE TITLE
it doesn't track wrong answers given when I have set more number of attempts

### ISSUE THREAD

**Issue by SeemaSP** [Acutilis/adapt-tkhub-xAPI#3]
If I have set an mcq with multiple attempts it seems to just store the last answer given by the user:

browserChannelHandler:  completed component list_test Object { composer: "jsonMC_v1.0", timestamp: "2017-05-05T08:06:00.347Z", verb: "completed", object: "list_test", objType: "component", eventInfo: Object, text: "completed component list_test", extraData: Object, actor: Object }

With the selected answer as follows:
_selectedItems
0:Object
user answer
0:true
1:false
I am finding it difficult to understand what this means. 
I had selected the wrong answer in both the attempts. But I can't make much out of this. Can you please explain what this means?
Also does this extension require the spoor plugin to be used in adapt?

**Comment by ryanrolds** [comment]
As far as I understand it it's saying that the first option (0) was not selected, but the second option (1) was selected. It does not require the Spoor plugin.

**Comment by ryanrolds** [comment]
Please look at the statement generated from the event that was sent to the LRS, you should see it in the network portion of the web inspector. There should a be `result` property in the statement that has the data you're looking for. The object should conform to (https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#result), if you see any issues with it let us know.

**Comment by SeemaSP** [comment]
Thanks for the response. But now I am facing another issue. I have set the adapt authoring tool with the 2 plugins that you mentioned:
    a. TrackerHub
    b. tkhub-xAPI
Now I have configured the trackerHUb as follows:
Is enabled: true
Course ID: http://10.1.1.13/
 Use Id: false
and for the browser channel handler:
 BrowserChannel (default): 

 Is enabled: false 
 Reports Events: false
 Tracks State: false
 Is State Source: false
 Is State Store: false
 Is Launch Manager:false 

And in my tkhub-xAPI I have configured it as follows:
tkhub xAPI Channel Handler:

 Is enabled: true

and the details of the channel added are:

 Channel name: LRS
 Is enabled: true
 Reports Events: true
 Tracks State: true
 Is State Source: true
 Is State Store: true
 Is Launch Manager: true

 xAPI Launch Method: adlxapi
 Is Fake LRS: false
 Home Page: 
 Mbox Identity: 
 Hardcoded user name: 
 Channel URL: 
 Username: 
 Password: 

As you can see, my intention was to set tkhub-xapi as my channel handler and not use the default one. Also I kept state source of browser handler to false because I wanted to read any state change from the LRS and not the local storage.

But after registering the course, the launch sequence is successful as I can see the sessionid and the proxy lrs endpoint received in response to the following POST request:
http://10.1.1.13:3000/launch/3dda.......64-3fc0-11ba8b763594
And this is the response:

{ actor: 
   { objectType: 'Agent',
     name: 'carc',
     account: 
      { homePage: 'http://10.1.1.13:3000/',
        name: 59....119cc4de1dd1b3 } },
  endpoint: 'http://10.1.1.13:3000/launch/3dda6....11ba8b763594/xAPI/',
  contextActivities: 
   { parent: 
      { id: 'http://10.1.1.13:3000/launches/3dd..........64-3fc0-11ba8b763594',
        definition: [Object] },
     grouping: 
      { id: 'http://10.1.1.13:3000/content/undefined',
        definition: [Object] } },
  customData: { launch: undefined, content: '' },
  sessionLength: 0,
  initializationCode: 0 }
 
and I even have the session id in the cookie(I guess from xapi-launch)
sfsdgtdfhgfhgjghj

But I see the page loading and it shows nothing. 
The other thing is that, if tkhub implements xapi-launch mechanism then I am unable to see in xapi-launch logs the launch token given back by tkhub-xAPI to xapi launch server. 

And becuase of this, the course launch id is not activated in xapi-launch server and it doesn't even store this log attempt in db.

I would appreciate if you could tell me where have I gone wrong with the configuration?

**Comment by jpablo128** [comment]
conversation moved to Gitter
